In [21]:
import re
import numpy as np

In [12]:
file_data = open('result_shuffle14400.txt', 'r')

print(type(file_data))
all_text = list(file_data)
# lines = file_data.readlines()
# print(lines[5])

file_data.close()

<class '_io.TextIOWrapper'>


In [14]:
import re

s = all_text[5]
result = re.sub(r"\D", "", s)
# print(result)
result = '0.' + result[2:]
print(float(result))

0.24182903335119288


In [15]:
tcca = [all_text[3], all_text[4], all_text[5], all_text[6]]
loss = []

for t in range(len(tcca)):
    result = re.sub(r"\D", "", tcca[t])
    result = result[1:2] + '.' + result[2:]
    loss.append(float(result))

print(loss)

[0.3056971320675479, 0.20587090332474972, 0.24182903335119288, 0.41048880513343544]


In [28]:
def single(aiueo):
    '返り値はリスト型の損失'
    loss = []
    tcca = aiueo

    for t in range(len(tcca)):
        result = re.sub(r"\D", "", tcca[t])
        result = result[1:2] + '.' + result[2:]
        loss.append(float(result))
    return loss


In [29]:
epoch = 3
start = 3

# all_loss = np.array([])
all_loss = []
for i in range(epoch):
    tcca = all_text[start:start+4]
    loss = single(tcca)
    all_loss.append(loss)

    start = start+12

print(all_loss)

[[0.3056971320675479, 0.20587090332474972, 0.24182903335119288, 0.41048880513343544], [0.19209889688839515, 0.10781753212213516, 0.08356094823425843, 0.3488416656023926], [0.17781567240340843, 0.08816524828887648, 0.06660156205503477, 0.3392459079209301]]


In [31]:
aiu = np.array(all_loss)

array([[0.30569713, 0.2058709 , 0.24182903, 0.41048881],
       [0.1920989 , 0.10781753, 0.08356095, 0.34884167],
       [0.17781567, 0.08816525, 0.06660156, 0.33924591]])

In [33]:
aiu.T

array([[0.30569713, 0.1920989 , 0.17781567],
       [0.2058709 , 0.10781753, 0.08816525],
       [0.24182903, 0.08356095, 0.06660156],
       [0.41048881, 0.34884167, 0.33924591]])

In [34]:
test = aiu[0]
test

array([0.30569713, 0.2058709 , 0.24182903, 0.41048881])

In [35]:
test.argmax()

3

In [36]:
test.argmin()

1

In [38]:
type(test[test.argmin()])

numpy.float64

In [47]:
each_min = np.array([])
for i in aiu.T:
    # each_min.append(i.max())
    each_min = np.hstack([each_min, i.min()])

each_min

array([0.17781567, 0.08816525, 0.06660156, 0.33924591])

In [40]:
aiu

array([[0.30569713, 0.2058709 , 0.24182903, 0.41048881],
       [0.1920989 , 0.10781753, 0.08356095, 0.34884167],
       [0.17781567, 0.08816525, 0.06660156, 0.33924591]])

In [49]:
tcca

['[INFO] Total     : epoch3 @train: loss = 0.17781567240340843\n',
 '[INFO] Class     : epoch3 @train: loss = 0.08816524828887648\n',
 '[INFO] Coordinate: epoch3 @train: loss = 0.06660156205503477\n',
 '[INFO] Angle     : epoch3 @train: loss = 0.3392459079209301\n']

In [56]:
sep = ' '
t = tcca[0].split(sep)[-1]
t

'0.17781567240340843\n'

In [61]:
target = 'loss = '
idx = tcca[0].find(target)
r = tcca[0][idx+len(target):]

print(r)

0.17781567240340843



In [58]:
idx

34

In [59]:
target

'loss = '

In [60]:
len(target)

7

In [64]:
name = 'aiueoka'
n = name[2:-3]
n

'ue'

In [65]:
import glob

files = glob.glob("*.txt")
print(files)

['result_shuffle28800.txt', 'result_mobile7200.txt', 'result_mobile14400.txt', 'result_shuffle14400.txt', 'result_shuffle7200.txt', 'result_mobile28800.txt', 'result_shuffle1200.txt', 'result_shuffle3600.txt']


In [66]:
import pandas as pd

In [70]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]
columns1= ['list1']
columns2= ['list2']
index= ['a', 'b', 'c']

df1 = pd.DataFrame(list1, index, columns1)
df2 = pd.DataFrame(list2, index, columns2)


In [71]:
df1

list1
a      1
b      2
c      3

In [75]:
print(pd.concat([df1, df2], axis=1))

   list1  list2
a      1      4
b      2      5
c      3      6


In [90]:
dfObj = pd.DataFrame(index=['total', 'class', 'coordinate', 'angle'])
print(dfObj)

Empty DataFrame
Columns: []
Index: [total, class, coordinate, angle]


In [95]:
# dfObj.append([1, 2, 3, 4])
se = pd.Series([1, 2, 3, 4], index=['total', 'class', 'coordinate', 'angle'],name='sample')

In [96]:
se

total         1
class         2
coordinate    3
angle         4
Name: sample, dtype: int64

In [94]:
se.name

'sample'

In [98]:
df_new = dfObj.assign(se.name, se)

TypeError: assign() takes 1 positional argument but 3 were given

In [99]:
se1 = se
se1

total         1
class         2
coordinate    3
angle         4
Name: sample, dtype: int64

In [114]:

se2 = pd.Series([5, 1, 3, 4], index=['total', 'class', 'coordinate', 'angle'],name='sample')

In [115]:
se1df = pd.DataFrame(se1)

In [116]:
se1df

sample
total            1
class            2
coordinate       3
angle            4

In [119]:
se1df = se1df.assign(sample2=se2)

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (3230820809.py, line 1)

In [118]:
se1df

sample  sample2
total            1        5
class            2        1
coordinate       3        3
angle            4        4

In [120]:
se1df['sample3'] = se2

In [121]:
se1df

sample  sample2  sample3
total            1        5        5
class            2        1        1
coordinate       3        3        3
angle            4        4        4

In [122]:
se1df['saiu'] = [1, 2, 3, 4]

In [123]:
se1df

sample  sample2  sample3  saiu
total            1        5        5     1
class            2        1        1     2
coordinate       3        3        3     3
angle            4        4        4     4

In [124]:
se1df['nparray'] = np.array([1, 2, 3, 4])

In [125]:
se1df

sample  sample2  sample3  saiu  nparray
total            1        5        5     1        1
class            2        1        1     2        2
coordinate       3        3        3     3        3
angle            4        4        4     4        4